import fs from "node:fs";
import { createRequire } from "node:module";
import os from "node:os";
import path from "node:path";
import picomatch from "picomatch";
import { relativePosix } from "../../utils/paths.js";
import { getSourceFiles, isAutoGenerated, isExcludedFromScan } from "../../utils/source-files.js";
import { runSubprocess } from "../../utils/subprocess.js";
import { prefixUnusedVars, type UnusedVarTarget } from "../code-quality/unused-var-rename.js";
import type { Diagnostic, EngineContext } from "../types.js";
import { createOxlintConfig, type TestFramework } from "./oxlint-config.js";
import {
	clearSstReferenceCache,
	detectAmbientSources,
	fileReferencesSstPlatform,
	isAmbientFalsePositive,
	isRuntimeGlobalFalsePositive,
} from "./oxlint-context-filters.js";
import { collectAmbientGlobals, collectEslintIgnorePatterns } from "./oxlint-globals.js";

const esmRequire = createRequire(import.meta.url);

interface OxlintDiagnostic {
	message: string;
	code: string;
	severity: "warning" | "error";
	help: string;
	filename: string;
	labels: Array<{ span: { line: number; column: number } }>;
}

interface OxlintOutput {
	diagnostics: OxlintDiagnostic[];
}

type AmbientSources = ReturnType<typeof detectAmbientSources>;

const OXLINT_EXTENSIONS = new Set([".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs"]);

const resolveOxlintBinary = (): string => {
	try {
		const oxlintMainPath = esmRequire.resolve("oxlint");
		const oxlintDir = path.resolve(path.dirname(oxlintMainPath), "..");
		return path.join(oxlintDir, "bin", "oxlint");
	} catch {
		return "oxlint";
	}
};

const VITE_QUERY_RE = /["'][^"']*\?(worker|sharedworker|worker-url|url|raw|inline|init)\b/;
const isViteVirtualImportFalsePositive = (rule: string, message: string): boolean =>
	rule.startsWith("import/") && VITE_QUERY_RE.test(message);

const UNUSED_VAR_IDENT_RE =
	/(?:Variable|Parameter|Catch parameter) '([^']+)' (?:is declared but never used|is caught but never used)/;
const isUnderscoreUnusedVar = (rule: string, message: string): boolean => {
	if (rule !== "eslint/no-unused-vars") return false;
	const match = UNUSED_VAR_IDENT_RE.exec(message);
	return match ? match[1].startsWith("_") : false;
};

const readTextFile = (filePath: string): string | null => {
	try {
		return fs.readFileSync(filePath, "utf-8");
	} catch {
		return null;
	}
};

const isSolidRefFalsePositive = (context: EngineContext, diagnostic: Diagnostic): boolean => {
	if (diagnostic.rule !== "eslint/no-unassigned-vars") return false;
	const name = diagnostic.message.match(/^'([^']+)' is always 'undefined'/)?.[1];
	if (!name) return false;

	const absolutePath = path.isAbsolute(diagnostic.filePath)
		? diagnostic.filePath
		: path.join(context.rootDirectory, diagnostic.filePath);
	const content = readTextFile(absolutePath);
	if (!content) return false;

	const escaped = name.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
	return new RegExp(`\\bref=\\{\\s*${escaped}\\s*\\}`).test(content);
};

const isContextualTypeScriptFalsePositive = (diagnostic: Diagnostic): boolean =>
	diagnostic.rule === "typescript-eslint/triple-slash-reference" &&
	(diagnostic.filePath.endsWith(".d.ts") || /(?:^|\/)sst\.config\.ts$/.test(diagnostic.filePath));

const parseRuleCode = (code: string | null | undefined): { plugin: string; rule: string } => {
	if (!code) return { plugin: "eslint", rule: "syntax-error" };
	const match = code.match(/^(.+)\((.+)\)$/);
	if (!match) {
		// Plain code without parentheses (e.g. compile errors) — use "eslint" as default plugin
		return { plugin: "eslint", rule: code };
	}
	return { plugin: match[1].replace(/^eslint-plugin-/, ""), rule: match[2] };
};

const detectTestFramework = (rootDir: string): TestFramework => {
	try {
		const raw = fs.readFileSync(path.join(rootDir, "package.json"), "utf-8");
		const pkg = JSON.parse(raw) as Record<string, Record<string, string>>;
		const allDeps = { ...pkg.dependencies, ...pkg.devDependencies };

		if (allDeps.vitest) return "vitest";
		if (allDeps.jest || allDeps["ts-jest"] || allDeps["@jest/core"]) return "jest";
		if (allDeps.mocha) return "mocha";

		if (
			fs.existsSync(path.join(rootDir, "jest.config.js")) ||
			fs.existsSync(path.join(rootDir, "jest.config.ts")) ||
			fs.existsSync(path.join(rootDir, "jest.config.mjs"))
		)
			return "jest";
		if (
			fs.existsSync(path.join(rootDir, "vitest.config.ts")) ||
			fs.existsSync(path.join(rootDir, "vitest.config.js"))
		)
			return "vitest";
		if (fs.existsSync(path.join(rootDir, ".mocharc.yml"))) return "mocha";
	} catch {
		// ignore
	}
	return null;
};

const normalizeEslintIgnorePatterns = (patterns: string[]): string[] =>
	patterns
		.map((pattern) => pattern.trim().replace(/^\/+/, ""))
		.filter((pattern) => pattern.length > 0 && !pattern.startsWith("!"))
		.flatMap((pattern) => {
			if (pattern.endsWith("/*")) return [pattern.replace(/\/\*$/, "/**")];
			if (!pattern.includes("*") && !path.extname(pattern)) return [`${pattern}/**`];
			return [pattern];
		});

const isEslintIgnored = (relativePath: string, patterns: string[]): boolean =>
	patterns.length > 0 && picomatch.isMatch(relativePath, patterns, { dot: true });

const getOxlintTargets = (context: EngineContext): string[] => {
	const eslintIgnorePatterns = normalizeEslintIgnorePatterns(
		collectEslintIgnorePatterns(context.rootDirectory),
	);
	return getSourceFiles(context)
		.filter((filePath) => OXLINT_EXTENSIONS.has(path.extname(filePath).toLowerCase()))
		.filter((filePath) => !isAutoGenerated(filePath))
		.map((filePath) => path.relative(context.rootDirectory, filePath).split(path.sep).join("/"))
		.filter((filePath) => !isEslintIgnored(filePath, eslintIgnorePatterns));
};

const noUndefSeverityForContext = (context: EngineContext): "error" | "warn" =>
	context.languages.includes("php") ? "warn" : "error";

interface UnusedVarCandidate {
	filePath: string;
	line: number;
	column: number;
	name: string;
	type: "variable" | "parameter";
}

const extractUnusedVarName = (
	message: string,
): { name: string; type: "variable" | "parameter" } | null => {
	const variableMatch = message.match(/Variable '([^']+)' is declared but never used/);
	if (variableMatch?.[1]) return { name: variableMatch[1], type: "variable" };

	const paramMatch = message.match(/Parameter '([^']+)' is declared but never used/);
	if (paramMatch?.[1]) return { name: paramMatch[1], type: "parameter" };

	const catchMatch = message.match(/Catch parameter '([^']+)' is caught but never used/);
	if (catchMatch?.[1]) return { name: catchMatch[1], type: "parameter" };

	return null;
};

const collectUnusedVarCandidates = (diagnostics: Diagnostic[]): UnusedVarCandidate[] =>
	diagnostics
		.filter((d) => d.rule === "eslint/no-unused-vars")
		.map((d) => {
			const extracted = extractUnusedVarName(d.message);
			if (!extracted || extracted.name.startsWith("_")) return null;
			return {
				filePath: d.filePath,
				line: d.line,
				column: d.column,
				name: extracted.name,
				type: extracted.type,
			};
		})
		.filter((candidate): candidate is UnusedVarCandidate => candidate !== null);

const removeDuplicateKeyLines = (rootDirectory: string, diagnostics: Diagnostic[]): void => {
	const byFile = new Map<string, { key: string; line: number }[]>();

	for (const d of diagnostics) {
		const keyMatch = d.message.match(/Duplicate key '([^']+)'/);
		if (!keyMatch) continue;
		const absolute = path.isAbsolute(d.filePath)
			? d.filePath
			: path.join(rootDirectory, d.filePath);
		const entries = byFile.get(absolute) ?? [];
		entries.push({ key: keyMatch[1], line: d.line });
		byFile.set(absolute, entries);
	}

	for (const [filePath, dupes] of byFile) {
		if (!fs.existsSync(filePath)) continue;
		const content = fs.readFileSync(filePath, "utf-8");
		const lines = content.split("\n");
		const toRemove = new Set<number>();

		for (const { key } of dupes) {
			const escaped = key.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
			const keyPattern = new RegExp(`^\\s*['"]?${escaped}['"]?\\s*:|^\\s*${escaped}\\s*:`);

			const matches: number[] = [];
			for (let i = 0; i < lines.length; i++) {
				if (keyPattern.test(lines[i])) {
					matches.push(i);
				}
			}

			for (let j = 1; j < matches.length; j++) {
				toRemove.add(matches[j]);
			}
		}

		if (toRemove.size === 0) continue;
		const filtered = lines.filter((_, i) => !toRemove.has(i));
		fs.writeFileSync(filePath, filtered.join("\n"));
	}
};

const toDiagnostic = (d: OxlintDiagnostic): Diagnostic => {
	const { plugin, rule } = parseRuleCode(d.code);
	const label = d.labels[0];

	return {
		filePath: d.filename,
		engine: "lint",
		rule: `${plugin}/${rule}`,
		severity: d.severity,
		message: d.message.replace(/\S+\.\w+:\d+:\d+[\s\S]*$/, "").trim() || d.message,
		help: d.help || "",
		line: label?.span.line ?? 0,
		column: label?.span.column ?? 0,
		category: plugin === "react" ? "React" : plugin === "import" ? "Imports" : "Lint",
		fixable: false,
	};
};

const shouldKeepOxlintDiagnostic = (
	context: EngineContext,
	ambientSources: AmbientSources,
	seen: Set<string>,
	d: Diagnostic,
): boolean => {
	const relativePath = path.isAbsolute(d.filePath)
		? relativePosix(context.rootDirectory, d.filePath)
		: d.filePath;
	if (isExcludedFromScan(relativePath)) return false;
	if (isViteVirtualImportFalsePositive(d.rule, d.message)) return false;
	if (isAmbientFalsePositive(d.rule, d.message, ambientSources)) return false;
	if (isRuntimeGlobalFalsePositive(d.rule, d.message, context.rootDirectory, relativePath)) {
		return false;
	}
	if (isSolidRefFalsePositive(context, d)) return false;
	if (isContextualTypeScriptFalsePositive(d)) return false;
	if (isUnderscoreUnusedVar(d.rule, d.message)) return false;
	if (
		d.rule === "eslint/no-undef" &&
		fileReferencesSstPlatform(context.rootDirectory, d.filePath)
	) {
		return false;
	}
	const key = `${d.filePath}:${d.line}:${d.rule}:${d.message}`;
	if (seen.has(key)) return false;
	seen.add(key);
	return true;
};

export const runOxlint = async (context: EngineContext): Promise<Diagnostic[]> => {
	const configPath = path.join(os.tmpdir(), `aislop-oxlintrc-${process.pid}.json`);
	const framework = context.frameworks.find((f) => f !== "none");
	const testFramework = detectTestFramework(context.rootDirectory);
	const targets = getOxlintTargets(context);
	if (targets.length === 0) return [];
	const config = createOxlintConfig({
		framework,
		testFramework,
		globals: collectAmbientGlobals(context.rootDirectory),
		noUndefSeverity: noUndefSeverityForContext(context),
	});
	const ambientSources = detectAmbientSources(context.rootDirectory);
	clearSstReferenceCache();

	try {
		fs.writeFileSync(configPath, JSON.stringify(config, null, 2));

		const binary = resolveOxlintBinary();
		const args = [binary, "-c", configPath, "--format", "json"];

		const hasTs = context.languages.includes("typescript");
		if (hasTs && fs.existsSync(path.join(context.rootDirectory, "tsconfig.json"))) {
			args.push("--tsconfig", "./tsconfig.json");
		}

		args.push(...targets);

		const result = await runSubprocess(process.execPath, args, {
			cwd: context.rootDirectory,
			timeout: 120000,
		});

		if (!result.stdout) return [];

		let output: OxlintOutput;
		try {
			output = JSON.parse(result.stdout) as OxlintOutput;
		} catch {
			return [];
		}

		const seen = new Set<string>();
		return output.diagnostics
			.map(toDiagnostic)
			.filter((d) => shouldKeepOxlintDiagnostic(context, ambientSources, seen, d));
	} finally {
		if (fs.existsSync(configPath)) {
			fs.unlinkSync(configPath);
		}
	}
};

export const fixOxlint = async (
	context: EngineContext,
	options: { force?: boolean } = {},
): Promise<void> => {
	const dangerous = options.force ?? false;
	const configPath = path.join(os.tmpdir(), `aislop-oxlintrc-fix-${process.pid}.json`);
	const framework = context.frameworks.find((f) => f !== "none");
	const testFramework = detectTestFramework(context.rootDirectory);
	const targets = getOxlintTargets(context);
	if (targets.length === 0) return;
	const config = createOxlintConfig({
		framework,
		testFramework,
		mode: "fix",
		globals: collectAmbientGlobals(context.rootDirectory),
		noUndefSeverity: noUndefSeverityForContext(context),
	});

	try {
		fs.writeFileSync(configPath, JSON.stringify(config, null, 2));

		const binary = resolveOxlintBinary();
		const args = dangerous
			? [binary, "-c", configPath, "--fix", "--fix-suggestions", "--fix-dangerously", ...targets]
			: [binary, "-c", configPath, "--fix", ...targets];

		const result = await runSubprocess(process.execPath, args, {
			cwd: context.rootDirectory,
			timeout: 120000,
		});

		if (result.exitCode !== 0) {
			throw new Error(
				result.stderr || result.stdout || `Oxlint exited with code ${result.exitCode}`,
			);
		}

		const remaining = await runOxlint(context);
		const candidates = collectUnusedVarCandidates(remaining);
		if (candidates.length > 0) {
			const targets: UnusedVarTarget[] = candidates.map((c) => ({
				filePath: path.isAbsolute(c.filePath)
					? c.filePath
					: path.join(context.rootDirectory, c.filePath),
				line: c.line,
				column: c.column,
				name: c.name,
				type: c.type,
			}));
			prefixUnusedVars(context.rootDirectory, targets);
		}

		const duplicateKeys = remaining.filter((d) => d.message.startsWith("Duplicate key"));
		if (duplicateKeys.length > 0) {
			removeDuplicateKeyLines(context.rootDirectory, duplicateKeys);
		}
	} finally {
		if (fs.existsSync(configPath)) {
			fs.unlinkSync(configPath);
		}
	}
};
