import fs from "node:fs";
import path from "node:path";
import { relativePosix } from "../../utils/paths.js";
import { getSourceFiles, isAutoGenerated } from "../../utils/source-files.js";
import type { Diagnostic, EngineContext } from "../types.js";
import { type GoPackageSources, isGoDroppedError } from "./go-dropped-errors.js";

// Patterns for swallowed exceptions across languages
const SWALLOWED_EXCEPTION_PATTERNS: Array<{
	pattern: RegExp;
	languages: string[];
	message: string;
}> = [
	// JS/TS: catch with empty block or just comment
	{
		pattern: /catch\s*\([^)]*\)\s*\{\s*(?:\/\/[^\n]*)?\s*\}/,
		languages: [".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs"],
		message: "Empty catch block swallows errors silently",
	},
	// JS/TS: catch with only console.log (often AI pattern)
	{
		pattern: /catch\s*\([^)]*\)\s*\{\s*console\.log\([^)]*\);\s*\}/,
		languages: [".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs"],
		message: "Catch block only logs error without proper handling",
	},
	// Python: bare except/except Exception with pass
	{
		pattern: /except(?:\s+\w+)?:\s*\n\s*pass/,
		languages: [".py"],
		message: "Bare except with pass swallows errors silently",
	},
	// Go: ignoring error return
	{
		pattern: /\w+,\s*_\s*:?=\s*(\w+)\(/,
		languages: [".go"],
		message: "Error return value is being ignored",
	},
	// Ruby: rescue with no handling
	{
		pattern: /rescue(?:\s+\w+)?\s*(?:=>?\s*\w+)?\s*\n\s*(?:nil|#)/,
		languages: [".rb"],
		message: "Rescue block swallows errors silently",
	},
	// Java: catch with empty block
	{
		pattern: /catch\s*\(\w+\s+\w+\)\s*\{\s*(?:\/\/[^\n]*)?\s*\}/,
		languages: [".java"],
		message: "Empty catch block swallows errors silently",
	},
	// C#: truly-empty catch block (no statements). A catch whose body is only a
	// comment - line (`// ...`) OR block (`/* ... */`) - is treated as a documented
	// intentional catch and passes, so the two comment syntaxes behave the same.
	{
		pattern: /catch\s*(?:\([^)]*\))?\s*\{\s*\}/,
		languages: [".cs"],
		message: "Empty catch block swallows errors silently",
	},
	// C/C++: empty catch block. A body that is only a comment - line or block -
	// is treated as a documented intentional catch and passes (matches the C#
	// behavior: neither comment syntax satisfies the whitespace-only body).
	{
		pattern: /catch\s*\([^)]*\)\s*\{\s*\}/,
		languages: [".cpp", ".cc", ".cxx", ".c", ".h", ".hh", ".hpp", ".hxx"],
		message: "Empty catch block swallows errors silently",
	},
];

// Conventional names that document an intentionally-ignored exception.
const INTENTIONAL_IGNORE_NAMES = new Set([
	"ignored",
	"ignore",
	"tolerated",
	"expected",
	"unused",
	"_",
	"_e",
	"_err",
	"_ex",
	"_t",
]);

const CATCH_PARAM_RE = /catch\s*\(\s*(?:\w+\s+)?([\w$]+)/;
const RESCUE_PARAM_RE = /rescue(?:\s+[\w:]+)?\s*=>\s*([\w$]+)/;
const PYTHON_EXCEPT_RE = /^([ \t]*)except\b[^:\n]*:\s*(?:#.*)?$/;

const isIntentionalIgnore = (matchText: string, ext: string): boolean => {
	const re = ext === ".rb" ? RESCUE_PARAM_RE : CATCH_PARAM_RE;
	const m = re.exec(matchText);
	if (!m) return false;
	return INTENTIONAL_IGNORE_NAMES.has(m[1].toLowerCase());
};

const indentWidth = (line: string): number => line.match(/^[ \t]*/)?.[0].length ?? 0;

const extractIndentedBlock = (
	lines: string[],
	startLine: number,
	parentIndent: number,
): string[] => {
	const body: string[] = [];
	for (let i = startLine + 1; i < lines.length; i++) {
		const line = lines[i];
		const trimmed = line.trim();
		if (trimmed.length === 0) {
			body.push(line);
			continue;
		}
		if (indentWidth(line) <= parentIndent) break;
		body.push(line);
	}
	return body;
};

const parenDelta = (line: string): number =>
	(line.match(/\(/g) ?? []).length - (line.match(/\)/g) ?? []).length;

const isPythonPrintOnlyBody = (body: string[]): boolean => {
	let sawPrint = false;
	let inPrintCall = false;
	let printDepth = 0;

	for (const line of body) {
		const trimmed = line.trim();
		if (trimmed.length === 0 || trimmed.startsWith("#")) continue;
		if (inPrintCall) {
			printDepth += parenDelta(trimmed);
			if (printDepth <= 0) inPrintCall = false;
			continue;
		}
		if (/^print\s*\(/.test(trimmed)) {
			sawPrint = true;
			printDepth = parenDelta(trimmed);
			inPrintCall = printDepth > 0;
			continue;
		}
		if (trimmed === "pass") continue;
		return false;
	}

	return sawPrint;
};

const detectPythonPrintOnlyExceptions = (content: string, relativePath: string): Diagnostic[] => {
	const diagnostics: Diagnostic[] = [];
	const lines = content.split("\n");
	for (let i = 0; i < lines.length; i++) {
		const line = lines[i];
		const match = PYTHON_EXCEPT_RE.exec(line);
		if (!match) continue;
		const body = extractIndentedBlock(lines, i, match[1].length);
		if (!isPythonPrintOnlyBody(body)) continue;
		diagnostics.push({
			filePath: relativePath,
			engine: "ai-slop",
			rule: "ai-slop/swallowed-exception",
			severity: "error",
			message: "Catch block only prints error without proper handling",
			help: "Handle errors explicitly: log with context, rethrow, or return an error value",
			line: i + 1,
			column: 0,
			category: "AI Slop",
			fixable: false,
		});
	}
	return diagnostics;
};

export const detectSwallowedExceptions = async (context: EngineContext): Promise<Diagnostic[]> => {
	const files = getSourceFiles(context);
	const diagnostics: Diagnostic[] = [];
	const goPackages: GoPackageSources = new Map();

	for (const filePath of files) {
		if (isAutoGenerated(filePath)) continue;
		let content: string;
		try {
			content = fs.readFileSync(filePath, "utf-8");
		} catch {
			continue;
		}

		const ext = path.extname(filePath);
		const relativePath = relativePosix(context.rootDirectory, filePath);
		if (ext === ".py") {
			diagnostics.push(...detectPythonPrintOnlyExceptions(content, relativePath));
		}

		for (const { pattern, languages, message } of SWALLOWED_EXCEPTION_PATTERNS) {
			if (!languages.includes(ext)) continue;

			const regex = new RegExp(
				pattern.source,
				pattern.flags + (pattern.flags.includes("g") ? "" : "g"),
			);

			for (const match of content.matchAll(regex)) {
				if (isIntentionalIgnore(match[0], ext)) continue;
				if (
					ext === ".go" &&
					!isGoDroppedError(content, match.index, match[1], filePath, goPackages)
				) {
					continue;
				}
				const line = content.slice(0, match.index).split("\n").length;
				diagnostics.push({
					filePath: relativePath,
					engine: "ai-slop",
					rule: "ai-slop/swallowed-exception",
					severity: "error",
					message,
					help: "Handle errors explicitly: log with context, rethrow, or return an error value",
					line,
					column: 0,
					category: "AI Slop",
					fixable: false,
				});
			}
		}
	}

	return diagnostics;
};
