import fs from "node:fs";
import path from "node:path";
import { relativePosix } from "../../utils/paths.js";
import {
	getProjectSourceFiles,
	getSourceFiles,
	isAutoGenerated,
} from "../../utils/source-files.js";
import type { Diagnostic, EngineContext } from "../types.js";
import {
	checkJsImport,
	collectDeclaredModuleMatchers,
	extractJsImports,
} from "./hallucinated-imports-js.js";
import {
	jsDepsForFile,
	loadManifest,
	pythonDepsForFile,
	pythonImportRootForFile,
	readJson,
} from "./hallucinated-imports-manifest.js";
import { collectTsPathAliases } from "./js-import-aliases.js";
import { collectWorkspaceDirs } from "./js-workspaces.js";
import { isNonProductionPath } from "./non-production-paths.js";
import { collectFromInlineScriptMetadata } from "./python-dependency-parser.js";
import { PYTHON_IMPORT_TO_PIP, PYTHON_STDLIB } from "./python-data.js";

const JS_EXTENSIONS = new Set([".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs"]);
const PY_EXTENSIONS = new Set([".py"]);

const extractPyImports = (content: string): { spec: string; line: number }[] => {
	const lines = content.split("\n");
	const results: { spec: string; line: number }[] = [];
	let inDoc: string | null = null;
	let typeCheckIndent = -1;
	for (let i = 0; i < lines.length; i++) {
		const raw = lines[i];
		const line = raw.trim();

		if (inDoc) {
			if (line.includes(inDoc)) inDoc = null;
			continue;
		}
		if (line === "" || line.startsWith("#")) continue;

		// Triple-quoted strings (docstrings, usage examples) hold import-shaped prose, not imports.
		const triples = line.match(/"""|'''/g);
		if (triples) {
			if (triples.length % 2 === 1) inDoc = triples[triples.length - 1];
			continue;
		}

		const indent = raw.length - raw.trimStart().length;
		if (typeCheckIndent >= 0 && indent <= typeCheckIndent) typeCheckIndent = -1;
		// Imports under `if TYPE_CHECKING:` are type-only — often typeshed-internal or dev-only deps.
		if (/^if\s+(?:[\w.]+\.)?TYPE_CHECKING\b/.test(line)) {
			typeCheckIndent = indent;
			continue;
		}
		if (typeCheckIndent >= 0) continue;

		// from X import ... — skip relative imports starting with .
		const fromMatch = line.match(/^from\s+([\w.]+)\s+import\b/);
		if (fromMatch && !fromMatch[1].startsWith(".")) {
			results.push({ spec: fromMatch[1], line: i + 1 });
			continue;
		}
		// import X[, Y as Z, ...]
		const importMatch = line.match(/^import\s+([\w.,\s]+?)(?:\s+as\s+\w+)?\s*$/);
		if (importMatch) {
			for (const part of importMatch[1].split(",")) {
				const cleaned = part.trim().split(/\s+as\s+/)[0];
				if (cleaned && !cleaned.startsWith(".")) {
					results.push({ spec: cleaned, line: i + 1 });
				}
			}
		}
	}
	return results;
};

const normalizePyName = (name: string): string => name.toLowerCase().replace(/_/g, "-");

const isSafePythonModuleEntry = (
	candidate: string,
	rootDirectory: string,
	expectedType: "file" | "directory",
): boolean => {
	try {
		const stats = fs.lstatSync(candidate);
		if (stats.isSymbolicLink()) return false;
		if (expectedType === "file" ? !stats.isFile() : !stats.isDirectory()) return false;
		const realPath = fs.realpathSync(candidate);
		const relative = path.relative(rootDirectory, realPath);
		return relative === "" || (!relative.startsWith("..") && !path.isAbsolute(relative));
	} catch {
		return false;
	}
};

const isLocalPythonImport = (spec: string, filePath: string, rootDirectory: string): boolean => {
	const modulePath = spec.split(".").join(path.sep);
	let root: string;
	let searchDirectory: string;
	try {
		root = fs.realpathSync(rootDirectory);
		searchDirectory = path.dirname(fs.realpathSync(filePath));
	} catch {
		return false;
	}
	while (searchDirectory === root || searchDirectory.startsWith(`${root}${path.sep}`)) {
		const candidate = path.join(searchDirectory, modulePath);
		if (
			isSafePythonModuleEntry(`${candidate}.py`, root, "file") ||
			isSafePythonModuleEntry(candidate, root, "directory")
		) {
			return true;
		}
		if (searchDirectory === root) break;
		searchDirectory = path.dirname(searchDirectory);
	}
	return false;
};

const pyDepSatisfiesImportRoot = (root: string, pyDeps: Set<string>): boolean => {
	const normalized = normalizePyName(root);
	for (const dep of pyDeps) {
		if (dep === normalized || dep.startsWith(`${normalized}-`)) return true;
	}
	return false;
};

const checkPyImport = (
	spec: string,
	pyDeps: Set<string>,
	filePath: string,
	rootDirectory: string,
): string | null => {
	const root = spec.split(".")[0];
	if (PYTHON_STDLIB.has(root)) return null;
	if (isLocalPythonImport(spec, filePath, rootDirectory)) return null;
	if (pyDepSatisfiesImportRoot(root, pyDeps)) return null;
	const normalized = normalizePyName(root);
	const distributions = PYTHON_IMPORT_TO_PIP[root] ?? PYTHON_IMPORT_TO_PIP[normalized];
	if (distributions?.some((dist) => pyDeps.has(normalizePyName(dist)))) return null;
	return root;
};

const isProvidedImport = (spec: string, provided: string[], separator: string): boolean =>
	provided.some((name) => spec === name || spec.startsWith(`${name}${separator}`));

const withInlineScriptDeps = (content: string, pyDeps: Set<string> | null): Set<string> | null => {
	const scriptDeps = new Set(pyDeps);
	return collectFromInlineScriptMetadata(content, scriptDeps) ? scriptDeps : pyDeps;
};

export const detectHallucinatedImports = async (context: EngineContext): Promise<Diagnostic[]> => {
	const rootPkg = readJson(path.join(context.rootDirectory, "package.json"), context.rootDirectory);
	const workspaceDirs = collectWorkspaceDirs(context.rootDirectory, rootPkg);
	const manifest = loadManifest(context.rootDirectory);
	if (!manifest.hasJsManifest && !manifest.hasPyManifest && !context.languages.includes("python")) {
		return [];
	}
	const tsAliasMatchers = manifest.hasJsManifest
		? collectTsPathAliases(context.rootDirectory, workspaceDirs)
		: [];

	const provided = context.config.imports?.provided ?? [];
	const diagnostics: Diagnostic[] = [];
	const files = getSourceFiles(context);
	const projectFiles = getProjectSourceFiles(context);
	const declaredModuleMatchers = manifest.hasJsManifest
		? collectDeclaredModuleMatchers(projectFiles, context.rootDirectory)
		: [];

	for (const filePath of files) {
		const ext = path.extname(filePath);
		const isJs = JS_EXTENSIONS.has(ext);
		const isPy = PY_EXTENSIONS.has(ext);
		if (!isJs && !isPy) continue;
		if (isJs && !manifest.hasJsManifest) continue;
		if (isAutoGenerated(filePath)) continue;
		const pyDeps = isPy ? pythonDepsForFile(manifest, filePath, context.rootDirectory) : null;
		const pyImportRoot = isPy
			? pythonImportRootForFile(manifest, filePath, context.rootDirectory)
			: context.rootDirectory;

		let content: string;
		try {
			content = fs.readFileSync(filePath, "utf-8");
		} catch {
			continue;
		}
		const relPath = relativePosix(context.rootDirectory, filePath);
		if (isNonProductionPath(relPath)) continue;

		const jsDeps = isJs ? jsDepsForFile(manifest, filePath, context.rootDirectory) : null;
		const filePyDeps = isPy ? withInlineScriptDeps(content, pyDeps) : null;
		if (isPy && !filePyDeps) continue;
		const imports = isJs ? extractJsImports(content) : extractPyImports(content);
		for (const { spec, line } of imports) {
			if (isProvidedImport(spec, provided, isJs ? "/" : ".")) continue;
			const hallucinated = isJs
				? checkJsImport(
						spec,
						jsDeps ?? manifest.jsDeps,
						tsAliasMatchers,
						declaredModuleMatchers,
						filePath,
						context.rootDirectory,
					)
				: checkPyImport(spec, filePyDeps ?? manifest.pyDeps, filePath, pyImportRoot);
			if (!hallucinated) continue;
			const manifestLabel = isJs
				? "package.json"
				: "requirements files, pyproject.toml, or Pipfile";
			diagnostics.push({
				filePath: relPath,
				engine: "ai-slop",
				rule: "ai-slop/hallucinated-import",
				severity: "error",
				message: `Imports "${hallucinated}" but it's not declared in ${manifestLabel}${isPy ? " and isn't Python stdlib" : ""}`,
				help: "Most often this is an LLM hallucinating a plausible-sounding package name. Either add the package to your manifest, or correct the import. If your runtime provides it, list it under imports.provided in .aislop/config.yml.",
				line,
				column: 1,
				category: "AI Slop",
				fixable: false,
			});
		}
	}

	return diagnostics;
};
