import fs from "node:fs";
import path from "node:path";
import { relativePosix } from "../../utils/paths.js";
import { getSourceFiles, isAutoGenerated } from "../../utils/source-files.js";
import { maskStringsAndComments } from "../../utils/source-masker.js";
import type { Diagnostic, EngineContext } from "../types.js";
import { isNonProductionPath } from "./non-production-paths.js";

const JAVA_EXTENSIONS = new Set([".java"]);
const JAVA_TEST_PATH_RE = /(?:^|\/)src\/test\/|(?:Test|Tests|IT)\.java$/;
const MAIN_METHOD_RE = /\bpublic\s+static\s+void\s+main\s*\(/;
const PRINT_CALL_RE = /\bSystem\s*\.\s*(?:out|err)\s*\.\s*(?:println|print|printf|format)\s*\(/;
const IMPORT_RE = /^\s*import\s+(static\s+)?([\w.]+?)(\.\*)?\s*;/;
const CATCH_OPEN_RE = /\bcatch\s*\([^)]*\)\s*\{/g;
const PRINT_ONLY_STATEMENT_RE =
	/^(?:\w+\.printStackTrace\s*\(\s*\)|System\s*\.\s*(?:out|err)\s*\.\s*(?:println|print|printf|format)\s*\(.*\))$/s;
const THROWS_RE = /(\w+)\s*\([^()]*(?:\([^()]*\)[^()]*)*\)\s*(throws)\s+([\w.,\s]+?)\s*[{;]/g;
const BROAD_THROWABLES = new Set([
	"Exception",
	"Throwable",
	"java.lang.Exception",
	"java.lang.Throwable",
]);
const BROAD_THROWS_ALLOWED_METHODS = new Set(["main", "close", "call"]);

const finding = (
	filePath: string,
	line: number,
	rule: string,
	message: string,
	help: string,
): Diagnostic => ({
	filePath,
	engine: "ai-slop",
	rule,
	severity: "warning",
	message,
	help,
	line,
	column: 1,
	category: "AI Slop",
	fixable: false,
});

const lineAt = (content: string, index: number): number =>
	content.slice(0, index).split("\n").length;

const closingBrace = (masked: string, openIndex: number): number => {
	let depth = 0;
	for (let i = openIndex; i < masked.length; i++) {
		if (masked[i] === "{") depth++;
		else if (masked[i] === "}") {
			depth--;
			if (depth === 0) return i;
		}
	}
	return -1;
};

const isJavadocReference = (raw: string, name: string): boolean =>
	new RegExp(`@(?:link|linkplain|see|throws|exception|value)\\s+[\\w.#]*\\b${name}\\b`).test(raw);

const detectImports = (raw: string, masked: string, relPath: string): Diagnostic[] => {
	const diagnostics: Diagnostic[] = [];
	const rawLines = raw.split("\n");
	const maskedLines = masked.split("\n");
	const seen = new Map<string, number>();
	const importLines = new Set<number>();
	const imports: Array<{ line: number; name: string; full: string }> = [];
	for (let i = 0; i < maskedLines.length; i++) {
		const match = IMPORT_RE.exec(maskedLines[i]);
		if (!match) continue;
		importLines.add(i);
		const full = `${match[1] ? "static " : ""}${match[2]}${match[3] ?? ""}`;
		if (seen.has(full)) {
			diagnostics.push(
				finding(
					relPath,
					i + 1,
					"ai-slop/duplicate-import",
					`Duplicate import of ${full}`,
					"Remove the repeated import line",
				),
			);
			continue;
		}
		seen.set(full, i);
		if (!match[3]) imports.push({ line: i, name: match[2].split(".").pop() ?? "", full });
	}
	const body = maskedLines.filter((_, i) => !importLines.has(i)).join("\n");
	const rawBody = rawLines.filter((_, i) => !importLines.has(i)).join("\n");
	for (const { line, name, full } of imports) {
		if (!name || new RegExp(`\\b${name}\\b`).test(body) || isJavadocReference(rawBody, name))
			continue;
		diagnostics.push(
			finding(
				relPath,
				line + 1,
				"ai-slop/unused-import",
				`Unused import ${full}`,
				"Remove the import; nothing in this file references it",
			),
		);
	}
	return diagnostics;
};

const detectPrintLeftovers = (masked: string, relPath: string): Diagnostic[] => {
	if (MAIN_METHOD_RE.test(masked)) return [];
	return masked
		.split("\n")
		.flatMap((line, i) =>
			PRINT_CALL_RE.test(line)
				? [
						finding(
							relPath,
							i + 1,
							"ai-slop/console-leftover",
							"System.out/System.err print left in production code",
							"Remove the debugging print or use the project's logger",
						),
					]
				: [],
		);
};

const detectPrintOnlyCatches = (masked: string, relPath: string): Diagnostic[] => {
	const diagnostics: Diagnostic[] = [];
	for (const match of masked.matchAll(CATCH_OPEN_RE)) {
		const open = match.index + match[0].length - 1;
		const close = closingBrace(masked, open);
		if (close === -1) continue;
		const statements = masked
			.slice(open + 1, close)
			.split(";")
			.map((statement) => statement.trim())
			.filter(Boolean);
		if (statements.length === 0) continue;
		if (!statements.every((statement) => PRINT_ONLY_STATEMENT_RE.test(statement))) continue;
		diagnostics.push(
			finding(
				relPath,
				lineAt(masked, match.index),
				"ai-slop/swallowed-exception",
				"Catch block only prints the exception and carries on",
				"Handle the error, rethrow it (wrapped if needed), or log it through the project's logger with context",
			),
		);
	}
	return diagnostics;
};

const detectBroadThrows = (masked: string, relPath: string): Diagnostic[] => {
	const diagnostics: Diagnostic[] = [];
	for (const match of masked.matchAll(THROWS_RE)) {
		if (BROAD_THROWS_ALLOWED_METHODS.has(match[1])) continue;
		const thrown = match[3].split(",").map((name) => name.trim());
		const broad = thrown.find((name) => BROAD_THROWABLES.has(name));
		if (!broad) continue;
		const throwsIndex = match.index + match[0].indexOf(match[2], match[1].length);
		diagnostics.push(
			finding(
				relPath,
				lineAt(masked, throwsIndex),
				"ai-slop/java-broad-throws",
				`\`${match[1]}\` declares \`throws ${broad}\`, which hides the exceptions callers must handle`,
				"Declare the specific checked exceptions this method throws, or wrap them in a domain exception",
			),
		);
	}
	return diagnostics;
};

export const detectJavaPatterns = async (context: EngineContext): Promise<Diagnostic[]> => {
	const diagnostics: Diagnostic[] = [];
	for (const filePath of getSourceFiles(context)) {
		if (!JAVA_EXTENSIONS.has(path.extname(filePath))) continue;
		if (isAutoGenerated(filePath)) continue;
		let raw: string;
		try {
			raw = fs.readFileSync(filePath, "utf-8");
		} catch {
			continue;
		}
		const relPath = relativePosix(context.rootDirectory, filePath);
		const masked = maskStringsAndComments(raw, ".java");
		diagnostics.push(...detectImports(raw, masked, relPath));
		if (isNonProductionPath(relPath) || JAVA_TEST_PATH_RE.test(relPath)) continue;
		diagnostics.push(...detectPrintLeftovers(masked, relPath));
		diagnostics.push(...detectPrintOnlyCatches(masked, relPath));
		diagnostics.push(...detectBroadThrows(masked, relPath));
	}
	return diagnostics;
};
