import fs from "node:fs";
import { relativePosix } from "../../utils/paths.js";
import { getSourceFiles, isAutoGenerated } from "../../utils/source-files.js";
import { findUnknownDirectiveScope } from "../../utils/suppress.js";
import type { Diagnostic, EngineContext } from "../types.js";

const KNOWN_DIRECTIVES = ["aislop-ignore-next-line", "aislop-ignore-line", "aislop-ignore-file"];

const closestDirective = (scope: string): string | undefined => {
	const compact = scope.toLowerCase().replace(/[-_]/g, "");
	return KNOWN_DIRECTIVES.find(
		(directive) => directive.slice("aislop-ignore-".length).replace(/-/g, "") === compact,
	);
};

const unknownDirectiveDiagnostic = (filePath: string, line: number, scope: string): Diagnostic => {
	const suggestion = closestDirective(scope);
	return {
		filePath,
		engine: "ai-slop",
		rule: "ai-slop/unknown-directive",
		severity: "warning",
		message: `"aislop-ignore-${scope}" is not a suppression directive, so it suppresses nothing`,
		help: suggestion
			? `Did you mean "${suggestion}"?`
			: `Use ${KNOWN_DIRECTIVES.join(", ")}, or a bare aislop-ignore for the same line.`,
		line,
		column: 1,
		category: "AI Slop",
		fixable: false,
	};
};

export const detectUnknownDirectives = async (context: EngineContext): Promise<Diagnostic[]> => {
	const diagnostics: Diagnostic[] = [];
	for (const filePath of getSourceFiles(context)) {
		if (isAutoGenerated(filePath)) continue;
		let content: string;
		try {
			content = fs.readFileSync(filePath, "utf-8");
		} catch {
			continue;
		}
		if (!content.includes("aislop-ignore-")) continue;
		const relPath = relativePosix(context.rootDirectory, filePath);
		const lines = content.split(/\r?\n/);
		for (let i = 0; i < lines.length; i++) {
			const scope = findUnknownDirectiveScope(lines[i]);
			if (scope) diagnostics.push(unknownDirectiveDiagnostic(relPath, i + 1, scope));
		}
	}
	return diagnostics;
};
