import fs from "node:fs";
import path from "node:path";
import { relativePosix } from "../../utils/paths.js";
import { getSourceFiles, getTestFiles, isAutoGenerated } from "../../utils/source-files.js";
import { maskComments, masksAllMultilineLiterals } from "../../utils/source-masker.js";
import { findUnknownDirectiveScope } from "../../utils/suppress.js";
import type { Diagnostic, EngineContext } from "../types.js";

const DIRECTIVE_BASE = ["aislop", "ignore"].join("-");
const DIRECTIVE_PREFIX = `${DIRECTIVE_BASE}-`;
const KNOWN_DIRECTIVES = ["next-line", "line", "file"].map(
	(scope) => `${DIRECTIVE_PREFIX}${scope}`,
);

const closestDirective = (scope: string): string | undefined => {
	const compact = scope.toLowerCase().replace(/[-_]/g, "");
	return KNOWN_DIRECTIVES.find(
		(directive) => directive.slice(DIRECTIVE_PREFIX.length).replace(/-/g, "") === compact,
	);
};

const unknownDirectiveDiagnostic = (filePath: string, line: number, scope: string): Diagnostic => {
	const suggestion = closestDirective(scope);
	return {
		filePath,
		engine: "ai-slop",
		rule: "ai-slop/unknown-directive",
		severity: "warning",
		message: `"${DIRECTIVE_PREFIX}${scope}" is not a suppression directive, so it suppresses nothing`,
		help: suggestion
			? `Did you mean "${suggestion}"?`
			: `Use ${KNOWN_DIRECTIVES.join(", ")}, or a bare ${DIRECTIVE_BASE} for the same line.`,
		line,
		column: 1,
		category: "AI Slop",
		fixable: false,
	};
};

const isInsideComment = (line: string, maskedLine: string, scope: string): boolean => {
	const column = line.indexOf(`${DIRECTIVE_PREFIX}${scope}`);
	return column !== -1 && maskedLine[column] === " ";
};

const unknownDirectivesIn = (filePath: string, relPath: string, content: string): Diagnostic[] => {
	const ext = path.extname(filePath).toLowerCase();
	if (!masksAllMultilineLiterals(ext)) return [];
	const lines = content.split(/\r?\n/);
	const maskedLines = maskComments(content, ext).split(/\r?\n/);
	const diagnostics: Diagnostic[] = [];
	for (let i = 0; i < lines.length; i++) {
		const scope = findUnknownDirectiveScope(lines[i]);
		if (!scope) continue;
		if (!isInsideComment(lines[i], maskedLines[i] ?? "", scope)) continue;
		diagnostics.push(unknownDirectiveDiagnostic(relPath, i + 1, scope));
	}
	return diagnostics;
};

export const detectUnknownDirectives = async (context: EngineContext): Promise<Diagnostic[]> => {
	const diagnostics: Diagnostic[] = [];
	const files = new Set([...getSourceFiles(context), ...getTestFiles(context)]);
	for (const filePath of files) {
		if (isAutoGenerated(filePath)) continue;
		let content: string;
		try {
			content = fs.readFileSync(filePath, "utf-8");
		} catch {
			continue;
		}
		if (!content.includes(DIRECTIVE_PREFIX)) continue;
		const relPath = relativePosix(context.rootDirectory, filePath);
		diagnostics.push(...unknownDirectivesIn(filePath, relPath, content));
	}
	return diagnostics;
};
