// aislop-ignore-file duplicate-block
import fs from "node:fs";
import path from "node:path";
import { overrideRelativePath, resolveFilePolicy } from "../../config/overrides.js";
import { relativePosix } from "../../utils/paths.js";
import { getSourceFiles, isAutoGenerated } from "../../utils/source-files.js";
import { CPP_SOURCE_EXTENSIONS } from "../cpp-targets.js";
import type { Diagnostic, EngineContext } from "../types.js";
import { CPP_FILE_LOC_MULTIPLIERS, CPP_FILE_TOO_LARGE_HELP } from "./complexity-cpp.js";
import { CSHARP_FILE_TOO_LARGE_HELP } from "./complexity-csharp.js";
import {
	analyzeFunctions,
	type FunctionInfo,
	isDataFile,
	isExemptFromComplexity,
} from "./complexity-functions.js";

export { analyzeFunctions } from "./complexity-functions.js";

interface QualityLimits {
	maxFunctionLoc: number;
	maxFileLoc: number;
	maxNesting: number;
	maxParams: number;
}

const FILE_LOC_MULTIPLIERS: Record<string, number> = {
	".tsx": 1.5,
	".jsx": 1.5,
	".rs": 2.5,
	".go": 1.5,
	...CPP_FILE_LOC_MULTIPLIERS,
};

const DECLARATION_FILE_RE = /\.d\.ts$/i;

const GENERIC_FILE_TOO_LARGE_HELP = "Consider splitting this file into smaller modules";

const fileTooLargeHelp = (ext: string): string => {
	if (CPP_SOURCE_EXTENSIONS.has(ext)) return CPP_FILE_TOO_LARGE_HELP;
	if (ext === ".cs") return CSHARP_FILE_TOO_LARGE_HELP;
	return GENERIC_FILE_TOO_LARGE_HELP;
};

const fileLocBudget = (ext: string, relativePath: string, base: number): number => {
	if (DECLARATION_FILE_RE.test(relativePath)) return Number.POSITIVE_INFINITY;
	const multiplier = FILE_LOC_MULTIPLIERS[ext] ?? 1;
	return Math.ceil(base * multiplier);
};

const checkFileDiagnostics = (
	relativePath: string,
	content: string,
	limits: QualityLimits,
): Diagnostic[] => {
	const results: Diagnostic[] = [];
	const lineCount = content.split("\n").length;
	const ext = path.extname(relativePath).toLowerCase();

	if (isDataFile(content)) return results;

	const configuredMax = fileLocBudget(ext, relativePath, limits.maxFileLoc);
	if (!Number.isFinite(configuredMax)) return results;
	const triggerAt = Math.ceil(configuredMax * 1.1);

	if (lineCount > triggerAt) {
		results.push({
			filePath: relativePath,
			engine: "code-quality",
			rule: "complexity/file-too-large",
			severity: "warning",
			message: `File too large (max: ${configuredMax})`,
			help: fileTooLargeHelp(ext),
			line: 0,
			column: 0,
			category: "Complexity",
			fixable: false,
			detail: `${lineCount} lines`,
		});
	}

	return results;
};

const JSX_EXTENSIONS = new Set([".tsx", ".jsx"]);
const isComponentFunction = (name: string, ext: string): boolean =>
	JSX_EXTENSIONS.has(ext) && /^[A-Z]/.test(name);

const functionLocBudget = (fn: FunctionInfo, ext: string, base: number): number => {
	if (isComponentFunction(fn.name, ext)) return Math.ceil(base * 2.0);
	if (ext === ".rs") return Math.ceil(base * 1.5);
	return base;
};

const checkFunctionDiagnostics = (
	relativePath: string,
	fn: FunctionInfo,
	limits: QualityLimits,
	ext: string,
): Diagnostic[] => {
	const results: Diagnostic[] = [];

	const fnMax = functionLocBudget(fn, ext, limits.maxFunctionLoc);
	const effectiveLineCount = fn.lineCount - fn.templateLines;
	if (effectiveLineCount > Math.ceil(fnMax * 1.1)) {
		results.push({
			filePath: relativePath,
			engine: "code-quality",
			rule: "complexity/function-too-long",
			severity: "warning",
			message: `Function too long (max: ${fnMax})`,
			help: "Consider breaking this function into smaller pieces",
			line: fn.startLine,
			column: 0,
			category: "Complexity",
			fixable: false,
			detail: `${fn.name} · ${fn.lineCount} lines`,
		});
	}

	if (fn.maxNesting > limits.maxNesting) {
		results.push({
			filePath: relativePath,
			engine: "code-quality",
			rule: "complexity/deep-nesting",
			severity: "warning",
			message: `Function nested too deeply (max: ${limits.maxNesting})`,
			help: "Consider using early returns or extracting nested logic",
			line: fn.startLine,
			column: 0,
			category: "Complexity",
			fixable: false,
			detail: `${fn.name} · depth ${fn.maxNesting}`,
		});
	}

	if (fn.paramCount > limits.maxParams) {
		results.push({
			filePath: relativePath,
			engine: "code-quality",
			rule: "complexity/too-many-params",
			severity: "warning",
			message: `Function has too many parameters (max: ${limits.maxParams})`,
			help: "Consider using an options object parameter",
			line: fn.startLine,
			column: 0,
			category: "Complexity",
			fixable: false,
			detail: `${fn.name} · ${fn.paramCount} params`,
		});
	}

	return results;
};

const checkFileComplexity = (
	filePath: string,
	rootDirectory: string,
	limits: QualityLimits,
): Diagnostic[] => {
	const relativePath = relativePosix(rootDirectory, filePath);
	if (isExemptFromComplexity(relativePath)) return [];

	let content: string;
	try {
		content = fs.readFileSync(filePath, "utf-8");
	} catch {
		return [];
	}

	const ext = path.extname(filePath).toLowerCase();
	const diagnostics = checkFileDiagnostics(relativePath, content, limits);

	for (const fn of analyzeFunctions(content, ext)) {
		diagnostics.push(...checkFunctionDiagnostics(relativePath, fn, limits, ext));
	}

	return diagnostics;
};

export const checkComplexity = async (context: EngineContext): Promise<Diagnostic[]> => {
	const files = getSourceFiles(context);
	const diagnostics: Diagnostic[] = [];

	for (const filePath of files) {
		if (isAutoGenerated(filePath)) continue;
		const { quality: limits } = resolveFilePolicy(
			context.config,
			overrideRelativePath(context.rootDirectory, filePath),
		);
		diagnostics.push(...checkFileComplexity(filePath, context.rootDirectory, limits));
	}

	return diagnostics;
};
